### PR TITLE
WIP: added npm-debug.log to gitignore list

### PR DESCRIPTION
**Pull request by kkasaei**
This is a test for Me. but I added a simple block to gitignore regarding npm_debug.log

### CODE REVIEW

**Comment by kentcdodds** [comment]
Cool! This is great. And congrats on [your first pull request](https://twitter.com/firstprbot/status/696846764117254148)

**Comment by kentcdodds** [comment]
MERGED! :tada: :confetti_ball:!

**Comment by kentcdodds** [comment]
Now that you've gotten this merged, wanna try your hand at some more stuff?

**Comment by kentcdodds** [comment]
Oh, also, you made this PR to my fork, why don't you make the same PR to the main repository :-)

**Comment by kkasaei** [comment]
well I was watching the course and doing it and at that point I though ti might be a good idea to branch it out. any I can update my Fork's pr/padLeft and continue on that . :) if That is what you mean.

Definitely I like to try more Stuff and I will. :+1:

**Comment by kkasaei** [comment]
Kent. Thanks again, for this course & your Support. It really helps..

**Comment by kentcdodds** [comment]
:+1:

**Pull request merged**
